### PR TITLE
ansible: install ciao from source code

### LINKED ISSUE #1086: ansbile: Install from source code
Remove option for installing from packages

### LINKED ISSUE #1089: ansible: Install OVMF firmware on compute and network hosts

### LINKED ISSUE #1090: ansible: Install dependencies for each role.
Dependencies where managed by the ciao packages.

We are now deploying from source code so dependencies should be preinstalled by ansible before
the ciao binary is run.

### LINKED ISSUE #1092: ansible: Use swupd plugin to install bundles in ClearLinux

### PR DESCRIPTION
**Pull request by albertomurillo**
This PR changes the way ciao is installed from packages to binaries.

Before we were installing packages built for each supported platform (ClearLinux, Ubuntu, Fedora) and those packages were responsible of installing the required dependencies.

The new approach is to install the ciao binaries on the destination hosts and handle the dependencies with ansible, this way we could achieve support for more OS without the burden of packaging ciao for each OS.

This is the initial step towards consolidation of production and development deployments under the same set of scripts.

Fixes #1086 
Fixes #1090 
Fixes #1089 
Fixes #1092

### CODE REVIEW

**Comment by markdryan** [comment]
@albertomurillo Is this good to go?

**Comment by albertomurillo** [comment]
From my side yes but i guess somoeone else need to test it

**Comment by markdryan** [comment]
I'll try to test it here on our Ubuntu cluster.

**Comment by markdryan** [comment]
I'm having some problems here.  Installing on an existing cluster I get

```
fatal: [ciao-ctl.ld.intel.com]: FAILED! => {"changed": false, "failed": true, "msg": "usermod: user ciao is currently used by process 16208\n", "name": "ciao", "rc": 8}
```

Once I fix this error I get

```
TASK [ciao-controller : Building CIAO and CIAO Development tools] **************
failed: [ciao-ctl.ld.intel.com] (item=github.com/01org/ciao/...) => {"changed": false, "cmd": "go get -v github.com/01org/ciao/...", "delta": "0:00:00.028133", "end": "2017-02-01 16:47:23.272770", "failed": true, "item": "github.com/01org/ciao/...", "rc": 1, "start": "2017-02-01 16:47:23.244637", "stderr": "package github.com/01org/ciao/...: cannot download, $GOPATH not set. For more details see: go help gopath", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by markdryan** [comment]
I'm testing with

```
ansible-playbook -i hosts ciao.yml --extra-vars "skip_ceph=true" --extra-vars "ciao_dev=true"
```

**Comment by albertomurillo** [comment]
The error while creating ciao user has been fixed

**Comment by albertomurillo** [comment]
`$GOPATH not set` error was due to missing 
```
        environment:
          GOPATH: "{{ gopath }}"
```
in the build task

**Comment by albertomurillo** [comment]
@markdryan This is ready to re-test

**Comment by markdryan** [comment]
@albertomurillo Could you improve the description of the PR, explain a little bit more about what this PR does and why?

**Comment by markdryan** [comment]
I still can't get it to work, although I am getting a different error.

```
failed: [CONTROLLER-NODE] (item=github.com/01org/ciao/...) => {"changed": false, "cmd": "go get -v github.com/01org/ciao/...", "delta": "0:03:33.776286", "end": "2017-02-02 12:27:46.723568", "failed": true, "item": "github.com/01org/ciao/...", "rc": 1, "start": "2017-02-02 12:24:12.947282", "stderr": "github.com/01org/ciao (download)\n# cd .; git clone https://github.com/01org/ciao /tmp/go/src/github.com/01org/ciao\nCloning into '/tmp/go/src/github.com/01org/ciao'...\nfatal: unable to access 'https://github.com/01org/ciao/': Failed to connect to github.com port 443: Connection timed out\npackage github.com/01org/ciao/...: exit status 128", "stdout": "", "stdout_lines": [], "warnings": []}
```

Could possibly be a proxy issue.  What I don't understand is where this command is executed and where the proxies are not set up correctly.  Does this run in the container from which I run ansible or does it run directly on the contrroller?

**Comment by markdryan** [comment]
And when I configure my proxies I get this:

```
(https fetch: Get https://golang.org/x/tools/go/gcimporter15?go-get=1: x509: failed to load system roots and no roots provided)", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by albertomurillo** [comment]
It runs on the container... that error might be related to the certificate issues we currently have in ClearLinux

**Comment by rbradford** [comment]
Fails with:

```
TASK [ciao-controller : Create configuration file] *****************************
task path: /home/rob/src/go/src/github.com/01org/ciao/_DeploymentAndDistroPackaging/ansible/roles/ciao-controller/tasks/startservices.yml:38
fatal: [ciao-ctl.ld.intel.com]: FAILED! => {"changed": false, "failed": true, "msg": "RepresenterError: cannot represent an object: 10.103.239.128/25"}
	to retry, use: --limit @/home/rob/src/go/src/github.com/01org/ciao/_DeploymentAndDistroPackaging/ansible/ciao.retry
```

**Comment by albertomurillo** [comment]
@rbradford That is a [bug](https://github.com/ansible/ansible/issues/20253) in ansible which is already fixed in ClearLinux but will be available in ansible>=2.2.2 for other distros.

I have updated this PR with a hack to make it work with ansible>=2.2.1.0 in other distros.

**Pull request merged**
