### PR TITLE
ciao-launcher: Use MiB in the launcher storage code

### PR DESCRIPTION
**Pull request by rbradford**
This makes us more consistent with the rest of ciao and general industry
expectations.

Fixes: #990

Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Comment by rbradford** [comment]
@markdryan to review

**Comment by tpepper** [comment]
Lgtm, but awaiting Mark

**Comment by markdryan** [comment]
The launcher changes look good but should we also change the names of payloads.Ready.DiskTotalMB and payloads.Stat.DiskTotalMB?  Should we also change the text in the WebUI from MB to MiB?

**Comment by rbradford** [comment]
@markdryan Will do - but i'll put those into a separate PR as they're quite widespread and should really change the database schemas.

**Comment by markdryan** [comment]
@rbradford Sounds good to me.

**Pull request merged**
