### PR TITLE
Minor SingleVM fixes

### PR DESCRIPTION
**Pull request by rbradford**
Fix a couple of nits left over from the integration of the images as volumes work.

### CODE REVIEW

**Comment by rbradford** [comment]
@mcastelino Please can you review as OWNER.

**Comment by mcastelino** [comment]
LGTM.

**Comment by rbradford** [comment]
@albertomurillo yes.

**Comment by markdryan** [comment]
> Now that images are stored in ceph the CNCI image will be converted back
> on by the controller. Let's save some time and not convert it before
> uploading.

This PR actually seems to slow down single VM on my setup.  I'm guessing this is because the qcow file is compressed and so considerably smaller than the raw file (357MB compared to 857MB).  On my setup, it takes 4.25 seconds to convert the cnci image to qcow and upload it while it takes 8 seconds to upload the raw image.  This surprises me a little bit as the uploader of qcow images still needs to wait for the conversion to take place.  In singleVM at least it seems the task of uploading the image takes longer than the conversion.

**Comment by albertomurillo** [comment]
+1

**Comment by markdryan** [comment]
@albertomurillo What are you +1ing?  Do you also see the slow down in Single VM setup.sh when applying this patch?

**Comment by albertomurillo** [comment]
The controller uses qemu-img convert to convert the image file to rbd block device.
There is no need to convert from qcow2 -> Raw -> RBD when it can be done directly qcow2 -> RBD

**Comment by markdryan** [comment]
Right now the code is doing

raw -> qcow2 -> RBD

The patch changes this to

raw -> RBD

Which reduces an unnecessary conversion.  Unfortunately, this actually slows things down presumably as the compressed qcow2 images are quicker to upload than the raw images.

**Comment by rbradford** [comment]
@markdryan dropped controversial change. :-)

**Pull request merged**
