### PR TITLE
ciao-launcher: Remove --server command line option

### PR DESCRIPTION
**Pull request by mcastelino**
Remove the --server option from the ciao-launcher. The SSNTP
server will be obtained from the certificate. With this change
the launcher no longer needs to create the ciao CNCI config
payload. It also does not need to generate the ciao config iso.

Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>

### CODE REVIEW

**Comment by mcastelino** [comment]
@markdryan can you review this and let me know if this addresses the issue that you flagged.

**Comment by markdryan** [comment]
@mcastelino Yes, the launcher changes look fine but the payload changes seem to break the payloads unit tests.

**Comment by markdryan** [comment]
@mcastelino  Actually the ciao-launcher/README.md file needs to be updated as well to remove the --server parameter.

**Comment by mcastelino** [comment]
@markdryan Addresses the review comments and fixed the payload failure.

**Pull request merged**
