### PR TITLE
Single VM Dev: Use the new ciao-cli logic + Bug fixes

### PR DESCRIPTION
**Pull request by mcastelino**
This commit fixes https://github.com/01org/ciao/issues/249
The qemu-nbd command sporadically fails. This is a bug in qemu-nbd
See https://bugzilla.redhat.com/show_bug.cgi?id=1111635
This is due to udev taking an unpredictable time to run
As a workaround the test calls "udevadm settle"  and retries the mount
a few times which fixes the issue.

This commit also fixes https://github.com/01org/ciao/issues/248
The SSH connectivity test failed sporadically. This was due to the
fact that the VM's may take long time to boot as the VM's are running
on two levels of virtualization.

The test now retries the SSH connetivity multiple times. However on
really slow hardware this test may not succeed and has to be run manually.

Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>

### CODE REVIEW

**Comment by mcastelino** [comment]
@markdryan These two changes should fix both the issues you have observed in your setup

**Comment by tpepper** [comment]
@markdryan I'm leaving this one for you to confirm/merge on Tuesday

**Comment by markdryan** [comment]
@mcastelino The SSH problem is definitely fixed.  I wasn't able to get nbd to fail so I couldn't check if your fix for the cnci image works.

However, I notice one weird different when applying this patch.  I no longer get any output from iperf.  I ran 5 times, and never saw any output.  Once I did get some errors,

```
Starting Client connecting to  172.16.0.4
iperf3: error - unable to connect to server: Connection refused
Starting Client connecting to  172.16.0.4
Starting Client connecting to  172.16.0.4
Starting Client connecting to  172.16.0.4
Starting Client connecting to  172.16.0.4
Starting Client connecting to  172.16.0.4
Starting Client connecting to  172.16.0.4
Starting Client connecting to  172.16.0.4
iperf3: error - unable to connect to server: Connection refused
iperf3: error - unable to connect to server: Connection refused
iperf3: error - unable to connect to server: Connection refused
iperf3: error - unable to connect to server: Connection refused
iperf3: error - unable to connect to server: Connection refused
iperf3: error - unable to connect to server: Connection refused
iperf3: error - unable to connect to server: Connection refused
Starting Client connecting to  172.16.0.4
ip
```

Without the patch I see

```
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 172.16.0.5, port 43364
[  5] local 172.16.0.4 port 5201 connected to 172.16.0.5 port 43366
[  7] local 172.16.0.4 port 5201 connected to 172.16.0.5 port 43368
[  9] local 172.16.0.4 port 5201 connected to 172.16.0.5 port 43370
[ 11] local 172.16.0.4 port 5201 connected to 172.16.0.5 port 43372
[ 13] local 172.16.0.4 port 5201 connected to 172.16.0.5 port 43374
[ 15] local 172.16.0.4 port 5201 connected to 172.16.0.5 port 43376
[ 17] local 172.16.0.4 port 5201 connected to 172.16.0.5 port 43378
[ 19] local 172.16.0.4 port 5201 connected to 172.16.0.5 port 43380
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec   328 MBytes  2.75 Gbits/sec                  
[  7]   0.00-1.00   sec   295 MBytes  2.47 Gbits/sec                  
[  9]   0.00-1.00   sec   323 MBytes  2.71 Gbits/sec                  
[ 11]   0.00-1.00   sec   321 MBytes  2.69 Gbits/sec                  
[ 13]   0.00-1.00   sec   308 MBytes  2.58 Gbits/sec                  
[ 15]   0.00-1.00   sec   312 MBytes  2.62 Gbits/sec                  
[ 17]   0.00-1.00   sec   309 MBytes  2.59 Gbits/sec                  
[ 19]   0.00-1.00   sec   303 MBytes  2.54 Gbits/sec                  
[SUM]   0.00-1.00   sec  2.44 GBytes  21.0 Gbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
...

I'm not sure why this might be.  Perhaps the sleep that drops from 30 to 5.
```

**Comment by markdryan** [comment]
Yep.  It seems to be the sleep before list-instances.  If I bump that back up to 30 secs I see the iperf traces.

**Comment by markdryan** [comment]
@mcastelino I'm afraid we'll need to rebase.  I merged #252 which updates the setup.sh file to use the new ciao-cli.

**Comment by mcastelino** [comment]
@markdryan Yes, it looks like in this setup it takes time for everything to come up. I will move the docker tests after the VM's have connectivity. That should be more reliable vs just increasing the timeout. 

Will also rebase.

**Comment by mcastelino** [comment]
@markdryan @tpepper The PR has been rebased and the docker issue fixed (hopefully).

**Pull request merged**
