### PR TITLE
Add configuration file support to ciao-launcher

### PR DESCRIPTION
**Pull request by obedmr**
In order to make it more easy to use in a production server environment and
make it ready for OS init systems like systemd or sysvinit, here are the new
proposed features:

  - "config" module for handling the CIAO config files parsing
    - This module would contain all modules default structs
  - New CIAO config sample file at etc/ciao/ciao.json
    - We'll have the following sections:
      - launcher
      - scheduler
      - controller
      - cnci-agent
  - If you don't have any configuration file, services will start with
    defaults that were set in config module
  - Once you have the /etc/ciao/ciao.json file and you edited as needed,
    you can start ciao-launcher as compute node:
    	$ ./cioa-launcher --network=cn
    - Parameters reading priorities are (first has higher priority):
      1. Values from In-command parameters (It overwrites below specified values)
      2. Values from /etc/ciao (It overwrites below specified values)
      3. Values from /usr/share/default/ciao/

Signed-off-by: Munoz, Obed N <obed.n.munoz@intel.com>

### CODE REVIEW

**Comment by markdryan** [comment]
@obedmr I stupidly added my comments in #56 instead of this PR.  Most still apply apart from the comment on the paths.  Could you check #56?

Also, I don't think it makes sense to put config.go in a separate package as it contains launcher specific code.  I'd move that file into launcher and change names of the variables so that they start with a lower case letter.  Obviously you can't do this for the structure that contains the Unmarshalled json.

**Comment by obedmr** [comment]
@markdryan , /me applying changes. Just a question. I may move the launcher structs to launcher code, but what if we keep the InitConfg and LoadConfigFile functions at config.go? Don't you think that it may be a repeated code if we also add into the other projects like ciao-controller, ciao-scheduler, etc?

I could just create the launcher struct for example, and pass it to the config.go for reading and loading the variables there. And then reuse the config.go for the rest of components. How is it?

**Comment by markdryan** [comment]
@obedmr  Right now InitConfig and LoadConfigFile are launcher specific as they take a CiaoConfig parameter.  If you can make them generic, then I agree it makes sense to leave them in a separate package.  LauncherConfig would need to move to launcher but I guess InitConfig could accept an interface{} parameter to which launcher would pass a *LauncherConfig.  Do we need to return usedFile?

**Comment by obedmr** [comment]
@markdryan ok, gotcha, let me make it more generic. Regarding the usedFile was just to have the record of what was the last taken config file. But It is not necessary certain at the end. Because user will only put those values he or she wants to change, the rest values would be taken from defaults.

**Pull request closed without merging**
