### PR TITLE
Enhance workload storage verification

### PR DESCRIPTION
**Pull request by rbradford**
Enhance the verification code used to verify storage specification in the workload definition at both a ciao-cli and ciao-controller level.

As part of this PR ciao-controller now expects and explicit source type which ciao-cli will now provide.

Fixes: #1026

### CODE REVIEW

**Comment by tpepper** [comment]
LGTM aside from the gocyclo complaint.

**Comment by kaccardi** [comment]
@rbradford does the README.md in ciao-cli/examples need to be updated to reflect this requirement, or is this change transparent to the user?

**Comment by rbradford** [comment]
@kaccardi not with *this* PR. I have another branch that deletes the image_id functionality. This just exercises what was already there and fixes it.

**Comment by rbradford** [comment]
@kaccardi yes this change is transparent to the user. It will in fact improve the user experience considerably with better error reporting.

**Pull request merged**
