### PR TITLE
Launcher testability tweaks

### PR DESCRIPTION
**Pull request by rbradford**
Some tweaks to improve usability/robustness when testing with ciao-launcher-server.  The loadClusterConfiguration() refactor was needed to make go cyclo happy, but I think that it does improve the readability of that code.

### CODE REVIEW

**Comment by markdryan** [comment]
Looks good to me.  Tested locally and with the single machine vm.

**Comment by mcastelino** [comment]
@rbradford you may need to rebase this PR

**Comment by rbradford** [comment]
@mcastelino rebased!

**Comment by mcastelino** [comment]
@rbradford looks like there is bug that shows up only on travis... local build works fine

[31;1mThe command "eval go get -t -v ./..." failed. Retrying, 2 of 3.[0m

github.com/01org/ciao/ciao-launcher
# github.com/01org/ciao/ciao-launcher
ciao-launcher/main.go:420: break label not defined: DONE

[31;1mThe command "eval go get -t -v ./..." failed. Retrying, 3 of 3.[0m

github.com/01org/ciao/ciao-launcher
# github.com/01org/ciao/ciao-launcher
ciao-launcher/main.go:420: break label not defined: DONE

[31;1mThe command "eval go get -t -v ./..." failed 3 times.[0m

**Comment by kaccardi** [comment]
looks good to me.

**Pull request merged**
