### PR TITLE
Use OVMF code shipped by the OS

### PR DESCRIPTION
**Pull request by albertomurillo**
ciao package for ubuntu and fedora now includes the optimized OVMF.fd
bios from clearlinux which provides faster boot times than those shipped
in ovmf/edk2-ovmf packages for ubuntu/fedora respectively.

### CODE REVIEW

**Comment by markdryan** [comment]
IIRC, in the early days of ciao, I had problems booting clearlinux images on Ubuntu when using the OVMF.md file shipped by Ubuntu.  This was an older version of Ubuntu in fairness, but to get the clear images to boot properly I needed to use the clearlinux OVMF.md file instead.  Have you tried getting launcher to boot a cleallinux VM on Ubuntu with these patches?  You need to ensure that you can ssh or netcat into the VM to see if it's running.

**Comment by albertomurillo** [comment]
I have an openstack cloud in ubuntu that boots clearlinux but doesn't allow me to ssh, maybe is the ovmf code and not the cloud image itself... I will test.

**Comment by albertomurillo** [comment]
This PR is ready to be merged.

I just tested in an ubuntu cluster and clearlinux vms launched with ubuntu's OVFM_CODE.fd bios (clear cloud and cnci image) are getting the right login key from cloud-init.

**Comment by tpepper** [comment]
Do we have performance data on how much slower instance start is on non-ClearLinux distros with this change?

**Comment by albertomurillo** [comment]
Using ciao-cli trace feature i got the following numbers when booting `clear-10820-cloud.img` with OVMF_CODE.fd from ubuntu vs OVMF.fd from clearlinux.

Using ubuntu's OVMF_CODE.fd bios
```
albertom@deadpool.intel.com ~ $ ciao-cli instance add -workload e35ed972-c46c-4aad-a1e7-ef103ae079a2 -label ubuntu
Created new instance: c7a8030c-d3d5-4e13-bf6a-413d787e3470
albertom@deadpool.intel.com ~ $ ciao-cli trace show -label ubuntu
Trace data for [ubuntu]:
        Number of instances: 1
        Total time elapsed     : 0.486016 seconds
        Average time elapsed   : 0.486016 seconds
        Average Controller time: 0.083001 seconds
        Average Scheduler time : 0.000000 seconds
        Average Launcher time  : 0.178997 seconds
        Controller variance    : 0.000000 seconds²
        Scheduler variance     : 0.000000 seconds²
        Launcher variance      : 0.000000 seconds²
```

Using ClearLinux OVMF.fd
```
albertom@deadpool.intel.com ~ $ ciao-cli instance add -workload e35ed972-c46c-4aad-a1e7-ef103ae079a2 -label clear
Created new instance: 7cf0169a-fc70-483f-bc09-d8d46afeb312
albertom@deadpool.intel.com ~ $ ciao-cli trace show -label clear
Trace data for [clear]:
        Number of instances: 1
        Total time elapsed     : 0.499977 seconds
        Average time elapsed   : 0.499977 seconds
        Average Controller time: 0.084007 seconds
        Average Scheduler time : 0.000966 seconds
        Average Launcher time  : 0.187004 seconds
        Controller variance    : 0.000000 seconds²
        Scheduler variance     : 0.000000 seconds²
        Launcher variance      : 0.000000 seconds²
```

**Comment by markdryan** [comment]
I wouldn't expect to see any difference in those numbers.  Launcher reports that an instance has booted as soon as qemu starts.  It doesn't actually wait until the bios or the OS has booted.  The only way to check this would be to get cloud-init to phone home.

**Comment by albertomurillo** [comment]
clear-10820-cloud.img vm booted in ubuntu compute node with clear OVMF.fd
```
root@788e3b6b-0858-4000-89e0-2421d4201436 ~ # systemd-analyze
Startup finished in 5.4104s (firmware) + 45.1ms (loader) + 280.4ms (kernel) + 1.5646s (userspace) = 7.3006s
root@5f0e7e78-0948-4e0c-9ba0-ce65c69def4f ~ # systemd-analyze
Startup finished in 5.3625s (firmware) + 45.2ms (loader) + 286.0ms (kernel) + 1.4655s (userspace) = 7.1593s
root@2b208988-871f-4af5-863f-c79e92c75b7e ~ # systemd-analyze
Startup finished in 5.4024s (firmware) + 45.1ms (loader) + 284.3ms (kernel) + 1.5764s (userspace) = 7.3083s
```

clear-10820-cloud.img vm booted in ubuntu compute node with ubuntu OVMF_CODE.fd
```
root@eb603ebc-2c65-40e8-884c-6e2806cb19f6 ~ # systemd-analyze
Startup finished in 9.0732s (firmware) + 45.2ms (loader) + 285.4ms (kernel) + 1.5808s (userspace) = 10.9846s
root@209edf0c-081f-406f-9499-e74a617cace8 ~ # systemd-analyze
Startup finished in 9.2477s (firmware) + 45.4ms (loader) + 287.1ms (kernel) + 1.5652s (userspace) = 11.1456s
root@129549b0-aba2-4677-9d10-81941b918849 ~ # systemd-analyze
Startup finished in 9.0433s (firmware) + 45.2ms (loader) + 292.3ms (kernel) + 1.5585s (userspace) = 10.9394s
```

**Comment by tpepper** [comment]
There's been some IRC discussion around this, but it needs recorded here.

I worry that we're almost 100% slower on a key metric if we don't have the optimized OVMF.  That's quite dramatic.  That leads me to think Ciao should ship its own preferred OVMF.  But that brings some license complexity.

@albertomurillo can you put this on the agenda for the next weekly meeting to discuss with the broader team?

**Comment by albertomurillo** [comment]
@erick0z is the owner of the task to ship the optimized ovmf code in ubuntu/fedora.

I think once the packages are ready I can use this PR to update the playbooks.

**Comment by albertomurillo** [comment]
@tpepper Latest version of ciao packages for ubuntu/fedora includes the clearlinux optimized OVMF.fd code. 

I have updated this PR to make use of them.

**Comment by mcastelino** [comment]
@tpepper @markdryan is this good to merge?

**Comment by tpepper** [comment]
I'm sorry I missed the email notification.  Yes this looks good to me after https://github.com/01org/ciao/pull/846#issuecomment-265806792

**Pull request merged**
