### PR TITLE
testutil: singlevm: use hostname to get primary interface

### PR DESCRIPTION
**Pull request by kaccardi**
use hostname -i to get the ciao ip address.

Signed-off-by: Kristen Carlson Accardi <kristen@linux.intel.com>

### CODE REVIEW

**Comment by markdryan** [comment]
@mcastelino Does this look okay to you?

**Comment by rbradford** [comment]
Not sure how this PR will interact with #696 as from the man page

>        -i, --ip-address
              Display the network address(es) of the host name. Note that this works only if the host name can be resolved. Avoid  using
              this option; use hostname --all-ip-addresses instead.

It could be that the change to modify /etc/hosts is giving the correct forward resolution that makes this work. Deferring to @mcastelino

**Comment by mcastelino** [comment]
@rbradford good observation. I have seen this fail sometimes... I think I have an idea to address this whole linking to the host business.. I will update https://github.com/01org/ciao/pull/695 to add this.

This make the single vm fully independent of the host (except the hostname)

**Comment by mcastelino** [comment]
@kaccardi @rbradford fixed this issue with an alternate implementation which eliminates the need to use the host IP completely.  https://github.com/01org/ciao/pull/696

Once that PR gets merged, I think we can drop this one?

**Comment by kaccardi** [comment]
ok, I'll close this pull request.

**Pull request closed without merging**
