### PR TITLE
A more generic ciao vendor

### PR DESCRIPTION
**Pull request by dlespiau**
Sitting next to Mark, I've been looking at ciao-vendor for the cc-oci-runtime vendoring, but did things by hand until now: I have a hand written packages.json and manually culled deps in vendor/.

It's time to bite the bullet and make ciao-vendor usable for other projects. With this PR it now works for cc-oci-runtime!

```
$ ciao-vendor packages
Package											Status		Repo				Version		License
github.com/01org/cc-oci-runtime/vendor/github.com/davecgh/go-spew/spew			Vendored	github.com/davecgh/go-spew	6d212800	ISC
github.com/01org/cc-oci-runtime/vendor/github.com/hyperhq/runv/hyperstart/api/json	Vendored	github.com/hyperhq/runv		28d48ac6	Apache v2.0
github.com/01org/cc-oci-runtime/vendor/github.com/pmezard/go-difflib/difflib		Vendored	github.com/pmezard/go-difflib	792786c7	BSD
github.com/01org/cc-oci-runtime/vendor/github.com/stretchr/testify/assert		Vendored	github.com/stretchr/testify	976c720a	MIT
```

### CODE REVIEW

**Comment by dlespiau** [comment]
Updated PR:

  - Tightened the check verifying cwd is indeed under the gopath by appending "src" to it. (As seen with Mark offline)

**Comment by markdryan** [comment]
Please update the commit messages to conform to the patch format outlined in the CONTRIBUTING.md file.

**Comment by dlespiau** [comment]
Having talked with Mark, it seems that a couple of missing summaries is the problem here. The commits are:
  - fixing typo in a comment
  - removing the x bit of a text file.

I don't think such a thing should be blocking, so trying to add an explicit exception in CONTRIBUTING.md: https://github.com/01org/ciao/pull/798

**Comment by dlespiau** [comment]
Updated PR: Added a sentence in the commit messages of "ciao-vendor: Fix depdenency typo" and "vendor: Remove the execution bit on packages.json".

**Pull request merged**
