### PR TITLE
ansible: create ciao-launcher role

### LINKED ISSUE #819: ansible: replace ciao-compute and ciao-network with ciao-launcher role
There is no need to have separate roles for ciao-compute and ciao-network since both are
starting the same binary. The role gets determined by the certificate

### PR DESCRIPTION
**Pull request by albertomurillo**
ciao-compute and ciao-network roles are basically the same with
minimal differences.

This change introduces ciao-launcher role that knows how to handle those
minimal differences and replaces ciao-compute and ciao-network roles.

Fixes #819

Signed-off-by: Alberto Murillo Silva <alberto.murillo.silva@intel.com>

### CODE REVIEW

**Comment by rbradford** [comment]
Hi @albertomurillo. Have you had someone else verify this change against a cluster. In particular if running against a cluster that has already been built?

**Comment by albertomurillo** [comment]
@rbradford This change introduces ciao-launcher.service but does not removes the old ciao-compute.service or ciao-network.service unit files unless cleanup/ciao.yml is run.

@erick0z Does this branch works for you?

**Comment by mcastelino** [comment]
@albertomurillo can you rebase this and let me know when its ready

**Comment by erick0z** [comment]
@albertomurillo It works for me. I've tested against a clean cluster environment.

**Pull request merged**
