### PR TITLE
ciao-controller: move OpenStack compute support to openstack pkg

### LINKED ISSUE #346: testing: compute service coverage
Much of the payloads/compute.go functions are arguably covered, but the coveralls tool isn't noticing. The gap there points at payloads/compute.go and ciao-controller/compute*.go really should be a package of their own focused on exposing an OpenStack Compute API on top of Ciao.  @kaccardi has expressed a desire to do some cleanup in this direction.

There's as much as 400 lines of code here not covered by test, which is statistically significant in our test coverage percentage.

### LINKED ISSUE #352: ciao apis are exported through the openstack compute api service
the ciao apis should be cleanly separated from the openstack compute apis - either by changing the service port or by changing the routes.

### LINKED ISSUE #406: migrate ciao-controller compute code to openstack compatibility package
move the compute API code out of ciao-controller and into the openstack compatibility package. Use the keystone middleware to add keystone token verification where needed.

### PR DESCRIPTION
**Pull request by kaccardi**
Move the apis that are OpenStack compatible to the new openstack
package so that they can be maintained there from now on. Create
a new api.go file to maintain ciao specific apis. Since our ciao
apis were previously exposed as openstack compute apis, create
a legacy_api.go file to maintain compatibility and documentation
for these old routes. Modify ciao-cli to import the types from
the new locations.

Fixes #406
Fixes #352
Fixes #346 

Signed-off-by: Kristen Carlson Accardi <kristen@linux.intel.com>

### CODE REVIEW

**Comment by kaccardi** [comment]
Needs UI testing to make sure I didn't break them.

**Comment by tpepper** [comment]
And...the do not merge note is there just b/c this is pending test with the webui?

**Comment by jorgevgut** [comment]
@arturonuman and I will check how it works with the UI, we'll let you know the result asap

**Comment by leoswaldo** [comment]
@kaccardi I took a review, and seems with your changes some API calls are not being generated, this was cause because the "Declarative comments" (as [example](https://github.com/01org/ciao/pull/567/files#diff-84d8ed874bbdc106addfff77f1ca51eaL595)) were removed ([here](https://github.com/01org/ciao/pull/567/files#diff-0e7a248ba10ef7a2571997b604d635feR215)) for each section.

Sections for Swagger missing to be generated:


**Flavors**
- [GET] /v2.1/{tenant}/flavors
- [GET] /v2.1/{tenant}/flavors/detail
- [GET] /v2.1/{tenant}/flavors/{flavor}
- [GET] /v2.1/flavors/{flavor}/servers/detail	


**Servers**
- [GET] /v2.1/{tenant}/servers/{server}
- [DELETE] /v2.1/{tenant}/servers/{server}
- [GET] /v2.1/{tenant}/servers/detail
- [POST] /v2.1/{tenant}/servers
- [POST] /v2.1/{tenant}/servers/{server}/action

**Comment by kaccardi** [comment]
@leoswaldo I added the missing swagger comments I think. Could you take another look? Note that the old endpoints are now implemented by two separate files: ciao-controller/legacy_api.go and openstack/compute/api.go

Thanks.

**Comment by jorgevgut** [comment]
@kaccardi Hi, we checked the UI, everything is working as expected.

**Comment by kaccardi** [comment]
since the UI isn't broken, I'm removing donotmerge label.

**Comment by leoswaldo** [comment]
LGTM, 

we'll need to change we generate the docs because we are having api outside ciao-controller dir (as openstack/compute/api.go), but thats part of other issue.

**Pull request merged**
