### PR TITLE
Issue55

### PR DESCRIPTION
**Pull request by albertomurillo**
A couple of commits to close issue #55

### CODE REVIEW

**Comment by mcastelino** [comment]
The systemd unit files will also need to be changed to accommodate this rename. 
Also the script files that generate the CNCI images need to comprehend the name change.
TravisCI today not check the validity of the CNCI and CNCI agent, hence it will not catch this error.

**Comment by mcastelino** [comment]
@albertomurillo looks good. I will test this on my cluster and merge.

**Comment by mcastelino** [comment]
Had to rebase make a few changes to merge this. Code is now merged.
There was a bug in one of the scripts which had to be fixed.

**Comment by albertomurillo** [comment]
Oh i was just rebasing that one but got into a meeting. Thanks!

**Pull request closed without merging**
