### PR TITLE
openstack: Export extractProject functionality

### LINKED ISSUE #1082: ciao-image, identity: Make tenant ID available in ciao-image service.
In order to support private images, image service requires tenant ID information. This will include changes on Ciao identity layer and ciao-image service itself.

### PR DESCRIPTION
**Pull request by obedmr**
Some service API requests in OpenStack will not contain the project/tenant
in them. It requires a mechanism for retrieving project data and make
the proper treatment of requests.

All API requests will contain a tokenID, this information can be used in
order to extract the tenant/project from identity service.

Fixes #1082

Signed-off-by: Obed N Munoz <obed.n.munoz@intel.com>

### CODE REVIEW

**Comment by rbradford** [comment]
@kaccardi needs to approve this.

**Comment by kaccardi** [comment]
@obedmr I think I'd like to see how you'd use it inside the image service. I'm I guess a little nervous about this - mainly because I wonder if we are letting ourselves get too dependent on the keystone layer, and I wonder if there might be some other way to do this that might be more generic. It'd probably help if I saw the way you were going to use the function.

**Comment by obedmr** [comment]
@kaccardi here's how image service would be using it. https://github.com/01org/ciao/pull/1123/files#diff-1fa51fda8b9d49d13b81a7985fcd7092R338

**Comment by mrkz** [comment]
@kaccardi I'd also be needing this for the privilege check in the Configuration API checks in ciao-controller, so I asked obed to create a different PR for this, hence I'm also looking forward to agree on how we would implement this.

**Comment by kaccardi** [comment]
@obedmr @mrkz i think I've got a way to do this that is a bit more generic - I'll post a PR in the next day or so.

**Comment by kaccardi** [comment]
I submitted a PR #1199 for review which allows the identity middleware to report whether a user is privileged or not. I was thinking if we also need the tenantID, we can similarly have the identity service report the tenantID in a context var rather than having the lower layers mess around with tokens.

**Comment by obedmr** [comment]
Hey @kaccardi, actually, we need the tenantID, it will allow the tenant-separated images, and the privileged user validation would help for public and internal images management.

**Comment by obedmr** [comment]
Closed in favor of using #1199

**Pull request closed without merging**
