### PR TITLE
ciao-cli: Initial Support for Cinder Volumes

### PR DESCRIPTION
**Pull request by albertomurillo**
Cinder is a block storage service for OpenStack

Added commands are:

ciao-cli volume [add list show update delete]

Signed-off-by: Alberto Murillo <alberto.murillo.silva@intel.com>

### CODE REVIEW

**Comment by sameo** [comment]
@albertomurillo The code looks good to me, but please add the gophercloud vendoring addition as a separate patch (to apply before the ciao-cli changes).

**Comment by markdryan** [comment]
It's best to do this as part of the same PR.  Check that you git status is clean in the fork you're using for this PR.

go run ciao-vendor/ciao-vendor.go vendor

This should pull the new packages into github.com/01org/ciao/vendor into your local workspace.  If you do a git status you'll be able to see them.

Add them all to a git commit and push the commit to this PR.  You can check everything is vendored correctly by running

go run ciao-vendor/ciao-vendor.go check

**Comment by sameo** [comment]
@albertomurillo Would you mind rebasing this PR and removing the DONOTMERGE prefix ?
It's time we go ahead and review/merge this one.

**Comment by sameo** [comment]
Looks good to me.
@markdryan Does the vendoring part look fine to you ?

**Comment by markdryan** [comment]
@sameo vendoring looks fine to me.

**Comment by tpepper** [comment]
@sameo I'll leave this and #398 for you to merge/rebase/merge coherently.

**Comment by sameo** [comment]
#401 is the rebased, revendored version of that PR.

**Pull request closed without merging**
